# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'first.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import user


class Login_page(object):
    def setupUi(self, Form):
        #Form.setObjectName("Form")
        Form.resize(570, 435)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(210, 280, 151, 51))
        self.pushButton.setStyleSheet("background-color:rgb(156, 123, 183);\n"
"font: 25 9pt \"Bookman Old Style\";\n"
"color: rgb(255, 255, 255);\n"
"font-size:20px;\n"
"font-weight:bold;\n"
"border : 0;")
        #self.pushButton.setObjectName("pushButton")
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setGeometry(QtCore.QRect(140, 160, 291, 31))
        self.textEdit.setStyleSheet("border : 5px;\n"
"\n"
"align:center;")
        #self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(Form)
        self.textEdit_2.setGeometry(QtCore.QRect(140, 210, 291, 31))
        self.textEdit_2.setStyleSheet("border : 5px;")
        #self.textEdit_2.setObjectName("textEdit_2")
        self.lineEdit = QtWidgets.QPushButton(Form)
        self.lineEdit.setGeometry(QtCore.QRect(0, 0, 571, 71))
        self.lineEdit.setStyleSheet("background-color:rgb(135, 39, 176);\n"
"font: 25 9pt \"Bookman Old Style\";\n"
"color: rgb(255, 255, 255);\n"
"font-size:20px;\n"
"font-weight:bold;\n"
"align:center;\n"
"text-align:center;\n"
"border : 5px;")
        #self.lineEdit.setObjectName("lineEdit")

        #self.lineEdit.clicked.connect(self.userPage)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "LOGIN PAGE"))
        self.pushButton.setText(_translate("Form", "login"))
        self.textEdit.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Gulim\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" dir=\'rtl\' style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:600;\">student number</span></p></body></html>"))
        self.textEdit_2.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Gulim\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:600;\">password</span></p></body></html>"))
        self.lineEdit.setText(_translate("Form", " POOC"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Login_page()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
