# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'user.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class UserPage(object):
    def setupUi(self, Form):
       #Form.setObjectName("Form")
        Form.resize(600, 480)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(0, 0, 231, 481))
        self.label.setStyleSheet("background-color : rgb(135, 39, 176);")
        self.label.setText("")
        #self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(20, 100, 191, 161))
        self.label_3.setStyleSheet("background-color : rgb(255, 184, 69);\n"
"border-radius : 50px;")
        self.label_3.setText("")
        #self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(230, 0, 371, 81))
        self.pushButton.setStyleSheet("background:rgb(208, 208, 208);\n"
"font: 75 10pt \"Arial Narrow\";\n"
"\n"
"")
        #self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(80, 320, 101, 31))
        self.label_2.setStyleSheet("color:rgb(255, 255, 255);\n"
"font: 75 10pt \"Agency FB\";")
        #self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(70, 280, 91, 41))
        self.label_4.setStyleSheet("color:rgb(255, 255, 255);\n"
"font: 75 14pt \"Bahnschrift SemiCondensed\";")
        #self.label_4.setObjectName("label_4")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 10, 81, 31))
        self.pushButton_2.setStyleSheet("background: rgb(74, 51, 88);\n"
"border:0;\n"
"color:rgb(255, 255, 255);\n"
"font: 75 12pt \"Agency FB\";")
        #self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(230, 80, 401, 81))
        self.pushButton_3.setStyleSheet("background:rgb(229, 229, 229);\n"
"font: 75 10pt \"Arial Narrow\";\n"
"")
        #self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(230, 160, 371, 81))
        self.pushButton_4.setStyleSheet("background:rgb(208, 208, 208);\n"
"font: 75 10pt \"Arial Narrow\";\n"
"\n"
"")
        #self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(Form)
        self.pushButton_5.setGeometry(QtCore.QRect(230, 240, 401, 81))
        self.pushButton_5.setStyleSheet("background:rgb(229, 229, 229);\n"
"font: 75 10pt \"Arial Narrow\";\n"
"")
        #self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(Form)
        self.pushButton_6.setGeometry(QtCore.QRect(230, 320, 371, 81))
        self.pushButton_6.setStyleSheet("background:rgb(208, 208, 208);\n"
"font: 75 10pt \"Arial Narrow\";\n"
"\n"
"")
        #self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(Form)
        self.pushButton_7.setGeometry(QtCore.QRect(230, 400, 401, 81))
        self.pushButton_7.setStyleSheet("background:rgb(229, 229, 229);\n"
"font: 75 10pt \"Arial Narrow\";\n"
"")
        self.pushButton_7.setObjectName("pushButton_7")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "USER PAGE"))
        self.pushButton.setText(_translate("Form", "인터넷 프로그래밍  A.M. 10:00                                   "))
        self.label_2.setText(_translate("Form", "사용자님"))
        self.label_4.setText(_translate("Form", "12191689"))
        self.pushButton_2.setText(_translate("Form", "Alert_Log"))
        self.pushButton_3.setText(_translate("Form", "이산수학   A.M. 9 : 50                                                           "))
        self.pushButton_4.setText(_translate("Form", "자바기반 응용 프로그래밍  P.M. 3:00                        "))
        self.pushButton_5.setText(_translate("Form", "통계학   A.M. 11 : 50                                                               "))
        self.pushButton_6.setText(_translate("Form", "오퍼레이팅 시스템    P.M. 1:00                                    "))
        self.pushButton_7.setText(_translate("Form", "댄스 스포츠   A.M. 10 : 00                                                     "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = UserPage()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
